AllCops:
  TargetRubyVersion: 3.2.2
  Exclude:
    - "**/vendor/**/*"
    - "**/*.gemspec"
    - "spec/**"
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/AsciiComments:
  Enabled: false